name: Scheduled Commit

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "marchelcde"
          git config --global user.email "marchelmanullang026@student.unsrat.ac.id"

      - name: Add, Commit and Push
        run: |
          git status
          git add belajar-golang-goroutine
          git add readme.md
          git commit -m "Sesi pagi - Auto Update" || echo "Tidak ada perubahan"
          git push origin master